---
version: '3'
services:
  app:
    build: .
    image: hexletcomponents/devops-example-app
  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: navyfessan/devops-example-caddy
