---
- hosts: all
  gather_facts: false
  tasks:
# Создаем общую сеть
  # Контейнеры добавленные в эту сеть, могут обращаться друг к другу по имени контейнера,
  # который становится dns именем
    - community.docker.docker_container:
        name: app  # имя используется как домен
        image: hexletcomponents/devops-example-app:{{ version }}
        restart_policy: always
        state: started
        ports: [3000:3000]
        env:
          NODE_ENV: production
