---
name: pull_request
on: [pull_request]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make compose-build
      - run: make compose-test-ci
      - run: make compose-lint-ci
      - run: docker pull navyfessan/devops-example-caddy:latest
      - run: docker tag navyfessan/devops-example-caddy:latest hexletcomponents/devops-example-caddy:${{ github.ref_name }}
      - run: docker push navyfessan/devops-example-caddy:${{ github.ref_name }}
